type_demand= {
    'long-sleeve':'អាវដៃវែង',
    'short-sleeve':'អាវដៃខ្លី',
    'trouser':'ខោជេីងវែង',
    'short':'ខោជេីងខ្លី',
    'bag':'កាបូប',
    'shoe':'ស្បែកជេីង',
    'pajamas':'រ៉ូប',
    'suit':'ឈុត',
    't-shirt':'អាវយឹត',
    'man':'បុរស​',
    'woman':'ស្រ្តី',
    'child':'កុមារ',
    'sport':'ឈុតស្ព័រ',
}