# Generated by Django 3.0.9 on 2020-08-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200804_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_publised',
            new_name='is_available',
        ),
    ]
