# Generated by Django 3.0.9 on 2020-08-11 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200811_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='product_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
