# Generated by Django 3.0.9 on 2020-08-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200811_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detail',
        ),
    ]
