# Generated by Django 3.0.9 on 2020-08-12 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='size',
        ),
    ]
