# Generated by Django 3.0.9 on 2020-08-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('long-sleeve', 'អាវដៃវែង'), ('short-sleeve', 'អាវដៃខ្លី'), ('trouser', 'ខោជេីងវែង'), ('short', 'ខោជេីងខ្លី'), ('bag', 'កាបូប'), ('shoe', 'ស្បែកជេីង'), ('pajamas', 'រ៉ូប'), ('suit', 'ឈុត'), ('t-shirt', 'អាវយឹត'), ('man', 'បុរស\u200b'), ('woman', 'ស្រ្តី'), ('child', 'កុមារ'), ('sport', 'ឈុតស្ព័រ')], default='Shirt', max_length=20),
        ),
    ]
