# Generated by Django 3.0.9 on 2020-08-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
