# Generated by Django 3.0.9 on 2020-08-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_product_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
    ]
